from frestu.feature_extraction.time_series.spectrum.extractor_fft import ExtractorFft
from frestu.feature_extraction.time_series.spectrum.extractor_spectrum_ma import ExtractorSpectrumMa
from frestu.feature_extraction.time_series.spectrum.extractor_spectrums_peak_ma import ExtractorSpectrumsPeakMa
from frestu.feature_extraction.time_series.spectrum.extractor_stft import ExtractorStft
from frestu.feature_extraction.time_series.spectrum.extractor_wavelet import ExtractorWavelet