from frestu.optimization.agent.trader.strategy.period.spectrum.optimizer_strategy_regular_interval import OptimizerStrategyRegularInterval
from frestu.optimization.agent.trader.strategy.period.spectrum.optimizer_strategy_regular_interval_multiple import OptimizerStrategyRegularIntervalMultiple
from frestu.optimization.agent.trader.strategy.period.spectrum.optimizer_strategy_regular_interval_stop_loss import OptimizerStrategyRegularIntervalStopLoss
from frestu.optimization.agent.trader.strategy.period.spectrum.optimizer_strategy_regular_interval_take_profit import OptimizerStrategyRegularIntervalTakeProfit
from frestu.optimization.agent.trader.strategy.period.spectrum.optimizer_strategy_regular_interval_take_profit_stop_loss import OptimizerStrategyRegularIntervalTakeProfitStopLoss