from frestu.agent.trader.strategy.oscillator.strategy_atr import *
from frestu.agent.trader.strategy.oscillator.strategy_cci import *
from frestu.agent.trader.strategy.oscillator.strategy_demarker import *
from frestu.agent.trader.strategy.oscillator.strategy_deviation_rate import StrategyDeviationRate
from frestu.agent.trader.strategy.oscillator.strategy_divergence import *
from frestu.agent.trader.strategy.oscillator.strategy_dmi_di import StrategyDmiDi
from frestu.agent.trader.strategy.oscillator.strategy_dmi_di_adx import StrategyDmiDiAdx
from frestu.agent.trader.strategy.oscillator.strategy_madc_raw import StrategyMadcRaw
from frestu.agent.trader.strategy.oscillator.strategy_madc_threshold_raw import StrategyMadcThresholdRaw
from frestu.agent.trader.strategy.oscillator.strategy_madc_threshold import StrategyMadcThreshold
from frestu.agent.trader.strategy.oscillator.strategy_madc import StrategyMadc
from frestu.agent.trader.strategy.oscillator.strategy_macd_raw import StrategyMacdRaw
from frestu.agent.trader.strategy.oscillator.strategy_macd_reverse import StrategyMacdReverse
from frestu.agent.trader.strategy.oscillator.strategy_macd_threshold_raw import StrategyMacdThresholdRaw
from frestu.agent.trader.strategy.oscillator.strategy_macd_threshold import StrategyMacdThreshold
from frestu.agent.trader.strategy.oscillator.strategy_macd_thresholds import StrategyMacdThresholds
from frestu.agent.trader.strategy.oscillator.strategy_macd import StrategyMacd
from frestu.agent.trader.strategy.oscillator.strategy_osci import StrategyOsci
from frestu.agent.trader.strategy.oscillator.strategy_momentum import *
from frestu.agent.trader.strategy.oscillator.strategy_rci import *
from frestu.agent.trader.strategy.oscillator.strategy_rsi import StrategyRsi
from frestu.agent.trader.strategy.oscillator.strategy_fast_stochastics import StrategyFastStochastics
from frestu.agent.trader.strategy.oscillator.strategy_slow_stochastics import StrategySlowStochastics