from frestu.agent.trader.strategy.trend.strategy_bb_cross_ma_sigma import StrategyBbCrossMaSigma
from frestu.agent.trader.strategy.trend.strategy_bb_masm_mstd_mssm import StrategyBbMasmMstdMssm
from frestu.agent.trader.strategy.trend.strategy_bb_masm_mstd import StrategyBbMasmMstd
from frestu.agent.trader.strategy.trend.strategy_bb_mas_mstd_mssm import StrategyBbMasMstdMssm
from frestu.agent.trader.strategy.trend.strategy_bb_mas_mstd_mss import StrategyBbMasMstdMss
from frestu.agent.trader.strategy.trend.strategy_bb_mas_mstd import StrategyBbMasMstd
from frestu.agent.trader.strategy.trend.strategy_double_bottom import *
from frestu.agent.trader.strategy.trend.strategy_double_top import *
from frestu.agent.trader.strategy.trend.strategy_gccd_raw import StrategyGccdRaw
from frestu.agent.trader.strategy.trend.strategy_gccd_threshold_raw import StrategyGccdThresholdRaw
from frestu.agent.trader.strategy.trend.strategy_gccd_threshold import StrategyGccdThreshold
from frestu.agent.trader.strategy.trend.strategy_gccd import StrategyGccd
from frestu.agent.trader.strategy.trend.strategy_gcdc_raw import StrategyGcdcRaw
from frestu.agent.trader.strategy.trend.strategy_gcdc_reverse import StrategyGcdcReverse
from frestu.agent.trader.strategy.trend.strategy_gcdc_threshold_raw import StrategyGcdcThresholdRaw
from frestu.agent.trader.strategy.trend.strategy_gcdc_threshold import StrategyGcdcThreshold
from frestu.agent.trader.strategy.trend.strategy_gcdc_thresholds import StrategyGcdcThresholds
from frestu.agent.trader.strategy.trend.strategy_gcdc import StrategyGcdc
from frestu.agent.trader.strategy.trend.strategy_granville import *
from frestu.agent.trader.strategy.trend.strategy_head_and_sholder_reverse import *
from frestu.agent.trader.strategy.trend.strategy_head_and_sholder import *
from frestu.agent.trader.strategy.trend.strategy_heikinashi_cross_raw_ha import StrategyHeikinashiCrossRawHa
from frestu.agent.trader.strategy.trend.strategy_heikinashi import StrategyHeikinashi
from frestu.agent.trader.strategy.trend.strategy_mau import StrategyMau
from frestu.agent.trader.strategy.trend.strategy_parabolic_sar import StrategyParabolicSar
from frestu.agent.trader.strategy.trend.strategy_rainbow import StrategyRainbow
from frestu.agent.trader.strategy.trend.strategy_rainbow_limiting_slope import StrategyRainbowLimitingSlope
from frestu.agent.trader.strategy.trend.strategy_resistance_line import *
from frestu.agent.trader.strategy.trend.strategy_support_line import *
from frestu.agent.trader.strategy.trend.strategy_trend_line import *